application: turra-rovers
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  
- url: /static
  static_dir: static

- url: /web
  static_dir: web

  
# Endpoints handler
- url: /_ah/spi/.*
  script: endPoints.api.app
  
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: endpoints
  version: 1.0
- name: pycrypto
  version: "latest"
