application: turra-rovers
version: 0.0.1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.app
  
-url: /static/.*
 static_dir: static
 
 
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest